services:
  db:
    container_name: shortage-shopify-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
